/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            tenantName: string;
            cnpj?: string;
            /** Format: email */
            phone?: string;
            email: string;
            password: string;
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              accessToken: string;
              refreshToken: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              accessToken: string;
              refreshToken: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            refreshToken: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              accessToken: string;
              refreshToken: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            refreshToken: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": "null" | null;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              userId: string;
              tenantId: string;
              role: string;
              name: string;
              email: string;
              plan: string;
              subscriptionStatus: string;
              isSubscriber: boolean;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              ok: true;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            token: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              ok: true;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspace/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              cnpj: string | null;
              industrySegment: string;
              taxRegime: string;
              createdAt: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            cnpj?: string;
            /** @enum {string} */
            industrySegment?:
              | "agencia"
              | "industria-leve"
              | "servicos-b2b"
              | "saas"
              | "varejo"
              | "geral";
            /** @enum {string} */
            taxRegime?: "simples" | "lucro-presumido" | "lucro-real";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              cnpj: string | null;
              industrySegment: string;
              taxRegime: string;
              createdAt: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/workspace/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              email: string;
              role: string;
              emailVerified: boolean;
              lastLoginAt: string | null;
            }[];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            name: string;
            /**
             * @default editor
             * @enum {string}
             */
            role?: "admin" | "editor" | "viewer";
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              email: string;
              role: string;
              emailVerified: boolean;
              lastLoginAt: string | null;
              tempPassword: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspace/members/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": "null" | null;
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/billing/subscription": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              plan: string;
              mode: string;
              status: string;
              trialEndsAt: string | null;
              currentPeriodStart: string | null;
              currentPeriodEnd: string | null;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/billing/checkout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            plan: "lite" | "pro" | "business";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uri */
              checkoutUrl: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/billing/portal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uri */
              portalUrl: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/billing/webhook": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/billing/success": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          session_id: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            monthlyAnalysis?: {
              /** @enum {string} */
              toneOfVoice?: "formal" | "informal";
              customInstructions?: string;
              minEntries?: number;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/config/whatsapp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              phone?: string;
              enabled?: boolean;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            phone?: string;
            enabled?: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/config/members/{userId}/role": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            role: "admin" | "editor" | "viewer";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              role: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/config/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              scopes: string[];
              lastUsedAt: string | null;
              expiresAt: string | null;
              createdAt: string;
            }[];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @default [] */
            scopes?: string[];
            expiresInDays?: number;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              scopes: string[];
              lastUsedAt: string | null;
              expiresAt: string | null;
              createdAt: string;
              token: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/tokens/{tokenId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          tokenId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": "null" | null;
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ingest/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ingest/clipboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            referenceMonth: string;
            text: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              analysisId: string;
              referenceMonth: string;
              entryCount: number;
              orphanCount: number;
              /** @enum {string} */
              outcome: "completed" | "partial" | "failed";
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ingest/manual": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            referenceMonth: string;
            entries: {
              date: string;
              description: string;
              amount: number | string;
              /** @enum {string} */
              direction: "credit" | "debit";
            }[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              analysisId: string;
              referenceMonth: string;
              entryCount: number;
              orphanCount: number;
              /** @enum {string} */
              outcome: "completed" | "partial" | "failed";
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/classification/{analysisId}/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          analysisId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                date: string;
                description: string;
                amountCents: number;
                direction: string;
                predictedCategory: string | null;
                confirmedCategory: string | null;
                classificationConfidence: number | null;
                correctionSource: string | null;
              }[];
              meta: {
                cursor: string | null;
                hasMore: boolean;
                total: number;
                requestId: string;
              };
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/classification/entries/{entryId}/correct": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          entryId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            category:
              | "receita_bruta"
              | "receita_financeira"
              | "outras_receitas"
              | "deducoes_receita"
              | "cpv_cmv"
              | "custo_servicos"
              | "despesas_pessoal"
              | "prolabore"
              | "despesas_administrativas"
              | "despesas_comerciais"
              | "despesas_ti"
              | "despesas_viagem"
              | "despesas_juridicas"
              | "despesas_financeiras"
              | "simples_nacional"
              | "irpj_csll"
              | "capex"
              | "emprestimos_entrada"
              | "amortizacao_dividas"
              | "transferencia_interna"
              | "depreciacao"
              | "outras_despesas"
              | "nao_classificado";
            /**
             * @default client
             * @enum {string}
             */
            source?: "rafael" | "client";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              confirmedCategory: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/analysis/{analysisId}/dre": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          analysisId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analysis/{analysisId}/narrative": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          analysisId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              cardType: string;
              title: string;
              body: string;
              evidence: {
                metric: string;
                value: number;
                unit: string;
              }[];
              clientApproved: boolean | null;
              clientComment: string | null;
            }[];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analysis/{analysisId}/narrative/{cardId}/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          analysisId: string;
          cardId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            approved: boolean;
            comment?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/analysis/{analysisId}/action-plan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          analysisId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: {
                id: string;
                /** @enum {string} */
                horizon: "short" | "medium" | "long";
                title: string;
                description: string;
                /** @enum {string} */
                effortLevel: "low" | "medium" | "high";
                /** @enum {string} */
                riskLevel: "low" | "medium" | "high";
                impactCents: number;
                deadlineDays: number | null;
                doneWhen: string | null;
                clientApproved: boolean | null;
                clientComment: string | null;
              }[];
              summary: {
                shortImpact: number;
                mediumImpact: number;
                longImpact: number;
                totalImpact: number;
              };
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analysis/{analysisId}/action-plan/{itemId}/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          analysisId: string;
          itemId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            approved: boolean;
            comment?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/analysis/{analysisId}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          analysisId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status: string;
              approvedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              type: string;
              title: string;
              status: number;
              detail?: string;
              instance?: string;
              requestId?: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/hub": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              subscription: {
                plan: string;
                mode: string;
                status: string;
              };
              latestAnalysis: {
                id: string;
                referenceMonth: string;
                status: string;
                mode: string;
                deliveredAt: string | null;
                approvedAt: string | null;
                dre: {
                  receitaBruta: number;
                  lucroLiquido: number;
                  margemLiquida: number;
                  ebitda: number;
                  margemEbitda: number;
                } | null;
                cards: {
                  critical_gap: number;
                  attention: number;
                  healthy: number;
                };
                actionPlan: {
                  total: number;
                  shortImpactCents: number;
                  mediumImpactCents: number;
                  longImpactCents: number;
                  totalImpactCents: number;
                } | null;
              } | null;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analyses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              analyses: {
                id: string;
                referenceMonth: string;
                status: string;
                mode: string;
                deliveredAt: string | null;
                approvedAt: string | null;
                costCents: number | null;
                totalImpactCents: number | null;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/analysis/{analysisId}/export/{type}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          analysisId: string;
          type: "monthly" | "investors" | "partners";
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
